# Generated by Django 4.0.5 on 2022-07-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='birth_date',
            new_name='birth_year',
        ),
    ]
