# Generated by Django 4.0.5 on 2022-07-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_duration_in_month_count',
            field=models.IntegerField(),
        ),
    ]
