# Generated by Django 4.0.5 on 2022-07-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_remove_category_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='tile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='urls',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
