# Generated by Django 4.0.5 on 2022-06-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_school_district_alter_useraccount_school_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='school_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
