# Generated by Django 4.0.5 on 2022-06-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useraccount_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
