# Generated by Django 4.0.5 on 2022-06-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_birth_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Birth',
        ),
    ]
