export const POST_PROJECT_REQUEST = 'POST_PROJECT_REQUEST'
export const POST_PROJECT_SUCCESS = 'POST_PROJECT_SUCCESS'
export const POST_PROJECT_FAIL = 'POST_PROJECT_FAIL'
export const POST_PROJECT_RESET = 'POST_PROJECT_RESET'

export const GET_PROJECTS_REQUEST = 'GET_PROJECTS_REQUEST'
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS'
export const GET_PROJECTS_FAIL = 'GET_PROJECTS_FAIL'
export const GET_PROJECTS_RESET = 'GET_PROJECTS_RESET'

export const GET_PROJECT_REQUEST = 'GET_PROJECT_REQUEST'
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS'
export const GET_PROJECT_FAIL = 'GET_PROJECT_FAIL'
export const GET_PROJECT_RESET = 'GET_PROJECT_RESET'