export const POST_CREATE_APPLICATION_REQUEST = 'POST_CREATE_APPLICATION_REQUEST'
export const POST_CREATE_APPLICATION_SUCCESS = 'POST_CREATE_APPLICATION_SUCCESS'
export const POST_CREATE_APPLICATION_FAIL = 'POST_CREATE_APPLICATION_FAIL'
export const POST_CREATE_APPLICATION_RESET = 'POST_CREATE_APPLICATION_RESET'

export const GET_APPLICATIONS_REQUEST = 'GET_APPLICATIONS_REQUEST'
export const GET_APPLICATIONS_SUCCESS = 'GET_APPLICATIONS_SUCCESS'
export const GET_APPLICATIONS_FAIL = 'GET_APPLICATIONS_FAIL'
export const GET_APPLICATIONS_RESET = 'GET_APPLICATIONS_RESET'

export const GET_APPLICATION_REQUEST = 'GET_APPLICATION_REQUEST'
export const GET_APPLICATION_SUCCESS = 'GET_APPLICATION_SUCCESS'
export const GET_APPLICATION_FAIL = 'GET_APPLICATION_FAIL'
export const GET_APPLICATION_RESET = 'GET_APPLICATION_RESET'