export const POST_ARTICLE_REQUEST = 'POST_ARTICLE_REQUEST'
export const POST_ARTICLE_SUCCESS = 'POST_ARTICLE_SUCCESS'
export const POST_ARTICLE_FAIL = 'POST_ARTICLE_FAIL'
export const POST_ARTICLE_RESET = 'POST_ARTICLE_RESET'

export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST'
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS'
export const GET_ARTICLES_FAIL = 'GET_ARTICLES_FAIL'
export const GET_ARTICLES_RESET = 'GET_ARTICLES_RESET'

export const GET_ARTICLE_REQUEST = 'GET_ARTICLE_REQUEST'
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS'
export const GET_ARTICLE_FAIL = 'GET_ARTICLE_FAIL'
export const GET_ARTICLE_RESET = 'GET_ARTICLE_RESET'