export const POST_COURSE_REQUEST = 'POST_COURSE_REQUEST'
export const POST_COURSE_SUCCESS = 'POST_COURSE_SUCCESS'
export const POST_COURSE_FAIL = 'POST_COURSE_FAIL'
export const POST_COURSE_RESET = 'POST_COURSE_RESET'

export const GET_COURSES_REQUEST = 'GET_COURSES_REQUEST'
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS'
export const GET_COURSES_FAIL = 'GET_COURSES_FAIL'
export const GET_COURSES_RESET = 'GET_COURSES_RESET'

export const GET_COURSE_REQUEST = 'GET_COURSE_REQUEST'
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS'
export const GET_COURSE_FAIL = 'GET_COURSE_FAIL'
export const GET_COURSE_RESET = 'GET_COURSE_RESET'

