export const GET_SCHOOL_REQUEST = 'GET_SCHOOL_REQUEST'
export const GET_SCHOOL_SUCCESS = 'GET_SCHOOL_SUCCESS'
export const GET_SCHOOL_FAIL = 'GET_SCHOOL_FAIL'
export const GET_SCHOOL_RESET = 'GET_SCHOOL_RESET'

export const GET_SUBJECT_CATEGORY_REQUEST = 'GET_SUBJECT_CATEGORY_REQUEST'
export const GET_SUBJECT_CATEGORY_SUCCESS = 'GET_SUBJECT_CATEGORY_SUCCESS'
export const GET_SUBJECT_CATEGORY_FAIL = 'GET_SUBJECT_CATEGORY_FAIL'
export const GET_SUBJECT_CATEGORY_RESET = 'GET_SUBJECT_CATEGORY_RESET'

export const GET_ARTICLE_CATEGORY_REQUEST = 'GET_ARTICLE_CATEGORY_REQUEST'
export const GET_ARTICLE_CATEGORY_SUCCESS = 'GET_ARTICLE_CATEGORY_SUCCESS'
export const GET_ARTICLE_CATEGORY_FAIL = 'GET_ARTICLE_CATEGORY_FAIL'
export const GET_ARTICLE_CATEGORY_RESET = 'GET_ARTICLE_CATEGORY_RESET'