export const POST_MESSAGE_REQUEST = 'POST_MESSAGE_REQUEST'
export const POST_MESSAGE_SUCCESS = 'POST_MESSAGE_SUCCESS'
export const POST_MESSAGE_FAIL = 'POST_MESSAGE_FAIL'
export const POST_MESSAGE_RESET = 'POST_MESSAGE_RESET'

export const GET_MESSAGES_REQUEST = 'GET_MESSAGES_REQUEST'
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS'
export const GET_MESSAGES_FAIL = 'GET_MESSAGES_FAIL'
export const GET_MESSAGES_RESET = 'GET_MESSAGES_RESET'

export const GET_MESSAGE_REQUEST = 'GET_MESSAGE_REQUEST'
export const GET_MESSAGE_SUCCESS = 'GET_MESSAGE_SUCCESS'
export const GET_MESSAGE_FAIL = 'GET_MESSAGE_FAIL'
export const GET_MESSAGE_RESET = 'GET_MESSAGE_RESET'