export const POST_RESULT_REQUEST = 'POST_RESULT_REQUEST'
export const POST_RESULT_SUCCESS = 'POST_RESULT_SUCCESS'
export const POST_RESULT_FAIL = 'POST_RESULT_FAIL'
export const POST_RESULT_RESET = 'POST_RESULT_RESET'

export const GET_RESULTS_REQUEST = 'GET_RESULTS_REQUEST'
export const GET_RESULTS_SUCCESS = 'GET_RESULTS_SUCCESS'
export const GET_RESULTS_FAIL = 'GET_RESULTS_FAIL'
export const GET_RESULTS_RESET = 'GET_RESULTS_RESET'

export const GET_RESULT_REQUEST = 'GET_RESULT_REQUEST'
export const GET_RESULT_SUCCESS = 'GET_RESULT_SUCCESS'
export const GET_RESULT_FAIL = 'GET_RESULT_FAIL'
export const GET_RESULT_RESET = 'GET_RESULT_RESET'

