// export const GET_SUBJECTS_REQUEST = 'GET_SUBJECTS_REQUEST'
// export const GET_SUBJECTS_SUCCESS = 'GET_SUBJECTS_SUCCESS'
// export const GET_SUBJECTS_FAIL = 'GET_SUBJECTS_FAIL'

export const GET_CATEGORY_SUBJECTS_REQUEST = 'GET_CATEGORY_SUBJECTS_REQUEST'
export const GET_CATEGORY_SUBJECTS_SUCCESS = 'GET_CATEGORY_SUBJECTS_SUCCESS'
export const GET_CATEGORY_SUBJECTS_FAIL = 'GET_CATEGORY_SUBJECTS_FAIL'
export const GET_CATEGORY_SUBJECTS_RESET = 'GET_CATEGORY_SUBJECTS_RESET'