export const GET_SUBJECTS_BY_CATEGORY_REQUEST = 'GET_SUBJECTS_BY_CATEGORY_REQUEST'
export const GET_SUBJECTS_BY_CATEGORY_SUCCESS = 'GET_SUBJECTS_BY_CATEGORY_SUCCESS'
export const GET_SUBJECTS_BY_CATEGORY_FAIL = 'GET_SUBJECTS_BY_CATEGORY_FAIL'
export const GET_SUBJECTS_BY_CATEGORY_RESET = 'GET_SUBJECTS_BY_CATEGORY_RESET'

export const GET_SUBJECT_BY_CATEGORY_REQUEST = 'GET_SUBJECT_BY_CATEGORY_REQUEST'
export const GET_SUBJECT_BY_CATEGORY_SUCCESS = 'GET_SUBJECT_BY_CATEGORY_SUCCESS'
export const GET_SUBJECT_BY_CATEGORY_FAIL = 'GET_SUBJECT_BY_CATEGORY_FAIL'
export const GET_SUBJECT_BY_CATEGORY_RESET = 'GET_SUBJECT_BY_CATEGORY_RESET'
